<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DosenKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dosens = [
            [
                'NIP' => 198711032014042001,
                'NIDN' => "0003118701",
                'Nama' => 'dr. Novriantika Lestari, M.Biomed.',
                'TTL' => 'Curup, 03-Nov-87',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/d',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198312252009121007,
                'NIDN' => "0025128301",
                'Nama' => 'dr. Zayadi Zainuddin, M.Pd.Ked., Sp.KFR',
                'TTL' => 'Rejang Lebong, 25-Dec-83',
                'CPNS' => '01-Dec-09',
                'Gol_Akhir' => 'III/d',
                'Pendidikan_Akhir' => 'S2/Sp1 UNPAD',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198309192009122003,
                'NIDN' => "0019098301",
                'Nama' => 'Dr. dr. Enny Nugraheni Sulistyorini, M.Biomed',
                'TTL' => 'Bengkulu, 19-Sep-83',
                'CPNS' => '01-Dec-09',
                'Gol_Akhir' => 'III/d',
                'Pendidikan_Akhir' => 'S3/Sp2 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198507062010121005,
                'NIDN' => "0006078501",
                'Nama' => 'Ddr. Ahmad Azmi Nasution, M.Biomed.',
                'TTL' => 'Rantau Rapat, Kab. Labuhan Batu, 06-Jul-85',
                'CPNS' => '01-Dec-10',
                'Gol_Akhir' => 'III/d',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198801152014042001,
                'NIDN' => "0015018801",
                'Nama' => 'dr. Riry Ambarsarie, M.Pd.Ked.',
                'TTL' => 'Bekasi, 15-Jan-88',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/d',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198212132014042001,
                'NIDN' => "0013128207",
                'Nama' => 'Dr. dr. Dessy Triana, M.Biomed.',
                'TTL' => 'Bengkulu, 13-Dec-82',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S3/Sp2 UNDIP',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198505012010122005,
                'NIDN' => "0001058502",
                'Nama' => 'dr. Hernita Taurustya, M.Biomed.',
                'TTL' => 'Argamakmur, Bengkulu Utara, 01-May-85',
                'CPNS' => '01-Dec-10',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UGM',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198702242010122007,
                'NIDN' => "0024028702",
                'Nama' => 'dr. Lala Foresta Valentine Gunasari, M.Biomed',
                'TTL' => 'Muncar, Kab. Banyuwangi, 24-Feb-87',
                'CPNS' => '01-Dec-10',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UGM',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198702182014042001,
                'NIDN' => "0018028701",
                'Nama' => 'dr. Utari Hartati Suryani, M.Kes',
                'TTL' => 'Curup, 18-Feb-87',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UNPAD',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198910112018032001,
                'NIDN' => "0011108901",
                'Nama' => 'Oktoviani, S.Farm., Apt., M.Farm.',
                'TTL' => 'Bengkulu, 11-Oct-89',
                'CPNS' => '01-Mar-18',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UNAND',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199008012019032011,
                'NIDN' => "0001089003",
                'Nama' => 'Liya Agustin Umar, S.Si, M.Biomed',
                'TTL' => 'Bengkulu, 01-Aug-90',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198806042019032015,
                'NIDN' => "0204068801",
                'Nama' => 'Mardhatillah Sariyanti, S.Si, M.Biomed',
                'TTL' => 'Bengkulu Selatan, 04-Jun-88',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199106042019032023,
                'NIDN' => "0004069105",
                'Nama' => 'Elvira Yunita, S.Si., M.Biomed.',
                'TTL' => 'Curup, 04-Jun-91',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198905192019032020,
                'NIDN' => "0119058901",
                'Nama' => 'Debie Rizqoh, S.Si., M.Biomed.',
                'TTL' => 'Tegal, 19-May-89',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198903262019031012,
                'NIDN' => "0326038903",
                'Nama' => 'Nikki Aldi Massardi, S.Si., M.Biomed.',
                'TTL' => 'Jakarta, 26-Mar-89',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199208062019032022,
                'NIDN' => "0006089201",
                'Nama' => 'Diah Ayu Aguspa Dita, S.Kep., Ns., M.Biomed.',
                'TTL' => 'Gunung Lewat, 06-Aug-92',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198405042009122006,
                'NIDN' => "0004058401",
                'Nama' => 'dr. Hilda Taurina, M.Sc.',
                'TTL' => 'Argamakmur, BU, 04-May-84',
                'CPNS' => '01-Dec-09',
                'Gol_Akhir' => 'III/c',
                'Pendidikan_Akhir' => 'S2/Sp1 UGM',
                'Jabfung_Akhir' => 'Lektor',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198301072008012006,
                'NIDN' => "0007018302",
                'Nama' => 'dr. Marisadonna Asteria, M.Biomed.',
                'TTL' => 'Bengkulu, 07-Jan-83',
                'CPNS' => '01-Jan-08',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UGM',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198512202009122002,
                'NIDN' => "0020128502",
                'Nama' => 'dr. Sylvia Rianissa Putri, M.Sc., Sp.P.',
                'TTL' => 'Medan, 20-Dec-85',
                'CPNS' => '01-Dec-09',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198607182010122004,
                'NIDN' => "0018078601",
                'Nama' => 'Dr. dr. Maria Eka Patri Yulianti, M.Biomed.',
                'TTL' => 'Dusun Baru, Mukomuko Utara, 18-Jul-86',
                'CPNS' => '01-Dec-10',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S3/Sp2 UNDIP',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198503032010122003,
                'NIDN' => "0003038501",
                'Nama' => 'dr. Sri Yunita, M.Biomed.',
                'TTL' => 'Bengkulu,  03-Mar-85',
                'CPNS' => '01-Dec-10',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198805252014042002,
                'NIDN' => "0025058801",
                'Nama' => 'dr. Elvira Rosana, M.Biomed.',
                'TTL' => 'Bengkulu Utara,  25-May-88',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UGM',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198703122014041001,
                'NIDN' => "0012038701",
                'Nama' => 'dr. Swandito Wicaksono, M.Biomed.',
                'TTL' => 'Banyumas,  12-Mar-87',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198605152015042001,
                'NIDN' => "0015058603",
                'Nama' => 'dr. Ike Sulistiyowati, M.Biomed., Sp.Rad.',
                'TTL' => 'Cirebon,  15-May-86',
                'CPNS' => '01-Apr-15',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UNIBRAW',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198707262014041001,
                'NIDN' => "0026078702",
                'Nama' => 'dr. Makbruri, M.Biomed.',
                'TTL' => 'Jakarta,  26-Jul-87',
                'CPNS' => '01-Apr-14',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198507012009122006,
                'NIDN' => "0001078501",
                'Nama' => 'dr. Noor Diah Erlinawati, M.Gizi, Sp.GK',
                'TTL' => 'Banyuwangi,  01-Jul-85',
                'CPNS' => '01-Dec-09',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198905052019032024                ,
                'NIDN' => "0005058910",
                'Nama' => 'dr. Rizkianti Anggraini, M.K.K',
                'TTL' => 'Curup,  05-May-89',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198712052019032013,
                'NIDN' => "0005128703",
                'Nama' => 'Ellen Maidia Djatmiko, S.Si., M.Biomed.',
                'TTL' => 'Palangkaraya,  05-Dec-87',
                'CPNS' => '01-Mar-19',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 198709142022032005,
                'NIDN' => "0014098703",
                'Nama' => 'dr. Hesty Rhauda Ashan, Sp.PK',
                'TTL' => 'Pekanbaru,  14-Sep-87',
                'CPNS' => '01-Mar-22',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UNAND',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199211132022032018,
                'NIDN' => "0013119206",
                'Nama' => 'Vernonia Yora Saki, M.K.M',
                'TTL' => 'Dharmasraya,  13-Nov-92',
                'CPNS' => '01-Mar-22',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Asisten Ahli',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199504062024062022,
                'NIDN' => "0006049503",
                'Nama' => 'dr. Indria Asrinda, M.Biomed.',
                'TTL' => 'Bengkulu,  06-Apr-95',
                'CPNS' => '01-Jun-24',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Tenaga Pengajar',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199402172024062001,
                'NIDN' => "0017029407",
                'Nama' => 'dr. Syeri Febriyanti, M.Epid.',
                'TTL' => 'Bengkulu,  17-Feb-94',
                'CPNS' => '01-Jun-24',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Tenaga Pengajar',
                'Homebase_PDDIKTI' => 'Pend. Profesi Dokter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'NIP' => 199701212024062002,
                'NIDN' => "0021019702",
                'Nama' => 'Kingkin Dia Pita Loka, S.Si., M.Biomed.',
                'TTL' => 'Bengkulu,  21-Jan-97',
                'CPNS' => '01-Jun-24',
                'Gol_Akhir' => 'III/b',
                'Pendidikan_Akhir' => 'S2/Sp1 UI',
                'Jabfung_Akhir' => 'Tenaga Pengajar',
                'Homebase_PDDIKTI' => 'S1 Kedokteran',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'NIP' => 196203102015081999,
            //     'Nama' => 'dr. Hamzah, MM',
            //     'TTL' => 'Aceh Selatan,  10-Mar-62',
            //     'Pendidikan_Akhir' => 'S2/Sp1 UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 195009272016011999                ,
            //     'Nama' => 'dr. Wahyu Sudarsono, MPH.',
            //     'TTL' => 'Surakarta,  27-Sep-50',
            //     'Pendidikan_Akhir' => 'S2/Sp1 UGM',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 198812102016032999                ,
            //     'Nama' => 'dr. Meutia Arini Yasrizal, MARS',
            //     'TTL' => 'Palembang,  10-Dec-88',
            //     'Pendidikan_Akhir' => 'S2/Sp1 UI',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 198812102016032999                ,
            //     'Nama' => 'dr. Meutia Arini Yasrizal, MARS',
            //     'TTL' => 'Palembang,  10-Dec-88',
            //     'Pendidikan_Akhir' => 'S2/Sp1 UI',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 1,
            //     'Nama' => 'dr. Arya Bintang Zhafari',
            //     'TTL' => 'Bengkulu,  25-Mar-94',
            //     'Pendidikan_Akhir' => 'S1/Prof UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 2,
            //     'Nama' => 'dr. Bella Yolanda',
            //     'TTL' => 'Bengkulu,  09-Sep-94',
            //     'Pendidikan_Akhir' => 'S1/Prof UNAND',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 3,
            //     'Nama' => 'dr. Fahrur Rozi Illahi',
            //     'TTL' => 'Bengkulu,  11-Nov-94',
            //     'Pendidikan_Akhir' => 'S1/Prof UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 4,
            //     'Nama' => 'dr. Istiqomah Katin',
            //     'TTL' => 'Bengkulu,  27-Jul-97',
            //     'Pendidikan_Akhir' => 'S1/Prof UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 5,
            //     'Nama' => 'dr. Meisa Nazthasia',
            //     'TTL' => 'Palembang,  20-May-94',
            //     'Pendidikan_Akhir' => 'S1/Prof UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 6,
            //     'Nama' => 'dr. M. Alif Qisthi Abi Rafdhi',
            //     'TTL' => 'Denpasar,  03-Dec-95',
            //     'Pendidikan_Akhir' => 'S1/Prof UNAND',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 7,
            //     'Nama' => 'dr. Muhammad Ridwan',
            //     'TTL' => 'Surulangun,  22-Apr-96',
            //     'Pendidikan_Akhir' => 'S1/Prof UNAND',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'NIP' => 8,
            //     'Nama' => 'dr. Tendri Ayu Putri Kahar',
            //     'TTL' => 'Bengkulu,  01-Jul-95',
            //     'Pendidikan_Akhir' => 'S1/Prof UNIB',
            //     'Jabfung_Akhir' => 'Tenaga Pengajar',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],



        ];

        // Masukkan data ke tabel dosens
        DB::table('dosens')->insert($dosens);

    }
}
